language: python
python:
#  - "2.6"
#  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "nightly"
matrix:
  allow_failures:
    - python: 2.6
    - python: 2.7
    - python: nightly
before_install:
	- sudo apt-get update -qq
# matplotlib dependencies
	- sudo apt-get install -qq build-essential python-dev python3-dev libpng12-dev libjpeg8-dev libfreetype6-dev
# command to install dependencies
install:
  - "python setup.py develop"
# command to run tests
script: py.test -v mandelbrot