language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
matrix:
  allow_failures:
    - python: 2.6
    - python: 2.7
    - python: nightly
# command to install dependencies
install:
  - "python setup.py develop"
# command to run tests
script: py.test -v mandelbrot