language: python
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "nightly"
  allow_failures:
    - python: "2.6"
    - python: "2.7"
    - python: "nightly"
before_install:
  - sudo apt-get update -qq
# matplotlib dependencies
  - sudo apt-get install -qq build-essential python-dev python3-dev libpng12-dev libjpeg8-dev libfreetype6-dev
# Cython is needed to install
  - pip install cython
# command to install dependencies
install:
  - travis_wait python setup.py develop
# command to run tests
script: py.test -v mandelbrot