language: python
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "nightly"
  allow_failures:
    - python: "2.6"
    - python: "2.7"
    - python: "nightly"
before_install:
  - sudo apt-get update -qq
# matplotlib dependencies
  - sudo apt-get install -qq build-essential python-dev python3-dev libpng12-dev libjpeg8-dev libfreetype6-dev
# Cython is needed to install
  - pip install cython
# Workarround for Python 3.2 problems installing matplotlib
# https://github.com/matplotlib/matplotlib/issues/3443/
  - if python --version 2>&1 | egrep -q "Python 3.2"; then pip install matplotlib==1.4.3; fi
install:
  - python setup.py develop
# command to run tests
script: py.test -v mandelbrot